sudo: true

# Use node_js environnement
language: node_js
node_js:
  - "10.15.0"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_PRD=fluted-set-227020
    - CLUSTER_NAME_PRD=cluster-1
    - CLOUDSDK_COMPUTE_ZONE=us-west1
    - DOCKER_IMAGE_NAME_PRODUCTION=status-bot
    - DOCKER_IMAGE_NAME_DEVELOPMENT=status-bot-development
    - KUBE_DEPLOYMENT_NAME=status-bot
    - KUBE_DEPLOYMENT_CONTAINER_NAME=status-bot
    - NODE_ENV=CI

install:
  - npm install

script:
  - npm test

before_deploy:
  - gcloud -v

deploy:
  - provider: script
    script: ./deploy-production.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./deploy-development.sh
    skip_cleanup: true
    on:
      branch: development