sudo: true

# Use node_js environnement
language: node_js
node_js:
  - "10.15.0"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_PRD=fluted-set-227020
    - CLUSTER_NAME_PRD=cluster-1
    - CLOUDSDK_COMPUTE_ZONE=us-west1
    - DOCKER_IMAGE_NAME=status-bot
    - KUBE_DEPLOYMENT_NAME=status-bot
    - KUBE_DEPLOYMENT_CONTAINER_NAME=status-bot
    - NODE_ENV=CI

install:
  - npm install

script:
  - npm test

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./deploy-production.sh
    skip_cleanup: true
    on:
      branch: master